app_env <- new.env(parent = globalenv())

source(file.path("R", "utils_paths.R"), local = app_env)

dependency_check <- app_env$check_app_dependencies()
if (!isTRUE(dependency_check$ok)) {
  stop(paste(dependency_check$messages, collapse = "\n"), call. = FALSE)
}

library(shiny)
library(AutoPlots)

app_env$APP_VERSION <- "1.0.0"
app_env$APP_RELEASE <- "1.0.0-buildweek"
app_env$MAX_UPLOAD_MB <- 50
options(shiny.maxRequestSize = app_env$MAX_UPLOAD_MB * 1024^2)

source(file.path("R", "service_result.R"), local = app_env)
source(file.path("R", "installation_paths.R"), local = app_env)
source(file.path("R", "installation_diagnostics.R"), local = app_env)
source(file.path("R", "package_launch.R"), local = app_env)
source(file.path("R", "technical_debt_register.R"), local = app_env)
source(file.path("R", "storage_architecture.R"), local = app_env)
source(file.path("R", "code_execution_policy.R"), local = app_env)
source(file.path("R", "code_runner_model.R"), local = app_env)
source(file.path("R", "service_code_runner.R"), local = app_env)
source(file.path("R", "custom_code_hooks.R"), local = app_env)
source(file.path("R", "registry_modules.R"), local = app_env)
source(file.path("R", "autoquant_shap_analysis_contracts.R"), local = app_env)
source(file.path("R", "module_result.R"), local = app_env)
source(file.path("R", "module_feature_preparation.R"), local = app_env)
source(file.path("R", "modeling_context.R"), local = app_env)
source(file.path("R", "feature_experiment_loop.R"), local = app_env)
source(file.path("R", "analytical_improvement_campaign.R"), local = app_env)
source(file.path("R", "module_autoquant_eda.R"), local = app_env)
source(file.path("R", "module_autoquant_model_readiness.R"), local = app_env)
source(file.path("R", "module_autoquant_regression_model_insights.R"), local = app_env)
source(file.path("R", "module_autoquant_binary_model_insights.R"), local = app_env)
source(file.path("R", "module_autoquant_regression_shap_analysis.R"), local = app_env)
source(file.path("R", "module_autoquant_binary_shap_analysis.R"), local = app_env)
source(file.path("R", "module_autoquant_catboost_builder.R"), local = app_env)
source(file.path("R", "artifact_model.R"), local = app_env)
source(file.path("R", "render_targets.R"), local = app_env)
source(file.path("R", "table_artifact_policy.R"), local = app_env)
source(file.path("R", "artifact_quality_policy.R"), local = app_env)
source(file.path("R", "project_artifact_collector.R"), local = app_env)
source(file.path("R", "artifact_studio_demo_seed.R"), local = app_env)
source(file.path("R", "product_experience_intelligence.R"), local = app_env)
source(file.path("R", "code_output_artifacts.R"), local = app_env)
source(file.path("R", "report_plan_model.R"), local = app_env)
source(file.path("R", "report_contract.R"), local = app_env)
source(file.path("R", "report_adapter_helpers.R"), local = app_env)
source(file.path("R", "report_regression_model_insights.R"), local = app_env)
source(file.path("R", "report_shap_analysis.R"), local = app_env)
source(file.path("R", "report_eda.R"), local = app_env)
source(file.path("R", "report_browser.R"), local = app_env)
source(file.path("R", "agent_operation.R"), local = app_env)
source(file.path("R", "build_week_demo_data.R"), local = app_env)
source(file.path("R", "table_theme.R"), local = app_env)
source(file.path("R", "table_render.R"), local = app_env)
source(file.path("R", "table_builders.R"), local = app_env)
source(file.path("R", "table_export.R"), local = app_env)
source(file.path("R", "data_loader.R"), local = app_env)
source(file.path("R", "registry_plots.R"), local = app_env)
source(file.path("R", "registry_options.R"), local = app_env)
source(file.path("R", "service_export.R"), local = app_env)
source(file.path("R", "service_plot.R"), local = app_env)
source(file.path("R", "plot_sizing_gallery.R"), local = app_env)
source(file.path("R", "project_state.R"), local = app_env)
source(file.path("R", "service_project.R"), local = app_env)
source(file.path("R", "project_bundle.R"), local = app_env)
source(file.path("R", "utils_messages.R"), local = app_env)
source(file.path("R", "genai_result_contracts.R"), local = app_env)
source(file.path("R", "genai_worker_contracts.R"), local = app_env)
source(file.path("R", "genai_actions.R"), local = app_env)
source(file.path("R", "genai_audit_ledger.R"), local = app_env)
source(file.path("R", "improvement_ledger.R"), local = app_env)
source(file.path("R", "remediation_plans.R"), local = app_env)
source(file.path("R", "genai_delegation.R"), local = app_env)
source(file.path("R", "genai_worker_runtime.R"), local = app_env)
source(file.path("R", "genai_job_manager.R"), local = app_env)
source(file.path("R", "cross_system_contracts.R"), local = app_env)
source(file.path("R", "cross_repo_validation.R"), local = app_env)
source(file.path("R", "cross_repo_impact_analysis.R"), local = app_env)
source(file.path("R", "async_job_service.R"), local = app_env)
source(file.path("R", "knowledge_compilation_runtime.R"), local = app_env)
source(file.path("R", "knowledge_compilation_runtime_phase4_active.R"), local = app_env)
source(file.path("R", "knowledge_compilation_runtime_phase5_active.R"), local = app_env)
source(file.path("R", "knowledge_compilation_runtime_phase6_active.R"), local = app_env)
source(file.path("R", "knowledge_compilation_runtime_phase7_active.R"), local = app_env)
source(file.path("R", "knowledge_compilation_runtime_phase8_active.R"), local = app_env)
source(file.path("R", "genai_service.R"), local = app_env)
source(file.path("R", "build_week_demo.R"), local = app_env)
source(file.path("R", "evidence_strategy_config.R"), local = app_env)
source(file.path("R", "evidence_routing_policy.R"), local = app_env)
source(file.path("R", "context_optimization_policy.R"), local = app_env)
source(file.path("R", "semantic_intelligence_workspace.R"), local = app_env)
source(file.path("R", "semantic_decision_lifecycle.R"), local = app_env)
source(file.path("R", "decision_valuation_workspace.R"), local = app_env)
source(file.path("R", "decision_workflow_workspace.R"), local = app_env)
source(file.path("R", "causal_intelligence_workspace.R"), local = app_env)
source(file.path("R", "causal_experiment_workspace.R"), local = app_env)
source(file.path("R", "causal_completed_experiment_workspace.R"), local = app_env)
source(file.path("R", "causal_itt_workspace.R"), local = app_env)
source(file.path("R", "causal_observational_workspace.R"), local = app_env)
source(file.path("R", "causal_cross_method_contracts.R"), local = app_env)
source(file.path("R", "epistemic_integrity_workspace.R"), local = app_env)
source(file.path("R", "working_contexts.R"), local = app_env)
source(file.path("R", "ui_components.R"), local = app_env)
source(file.path("R", "founder_testing_remediation.R"), local = app_env)
source(file.path("R", "command_palette.R"), local = app_env)
source(file.path("R", "page_guide.R"), local = app_env)
source(file.path("R", "page_knowledge_library.R"), local = app_env)
source(file.path("R", "page_mission_control.R"), local = app_env)
source(file.path("R", "page_evidence_review.R"), local = app_env)
source(file.path("R", "page_decision_management.R"), local = app_env)
source(file.path("R", "page_ai_runtime.R"), local = app_env)
source(file.path("R", "page_agent_operations.R"), local = app_env)
source(file.path("R", "page_build_week_demo.R"), local = app_env)
source(file.path("R", "page_product_experience.R"), local = app_env)
source(file.path("R", "global_ai_assistant.R"), local = app_env)
source(file.path("R", "page_project.R"), local = app_env)
source(file.path("R", "page_data.R"), local = app_env)
source(file.path("R", "page_plot_builder.R"), local = app_env)
source(file.path("R", "page_analysis_modules.R"), local = app_env)
source(file.path("R", "page_code_runner.R"), local = app_env)
source(file.path("R", "page_artifact_library.R"), local = app_env)
source(file.path("R", "page_layouts.R"), local = app_env)
source(file.path("R", "page_export.R"), local = app_env)
source(file.path("R", "page_report_browser.R"), local = app_env)
source(file.path("R", "page_workflow.R"), local = app_env)
source(file.path("R", "page_semantic_intelligence.R"), local = app_env)
source(file.path("R", "page_causal_intelligence.R"), local = app_env)
source(file.path("R", "app_ui.R"), local = app_env)
source(file.path("R", "app_server.R"), local = app_env)

ui <- app_env$build_app_ui()
server <- app_env$server

shinyApp(ui, server)
